"""testing autogenerate

Revision ID: e633cd2f68bb
Revises: b7de92234f2b
Create Date: 2026-02-10 09:24:33.961910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e633cd2f68bb'
down_revision: Union[str, Sequence[str], None] = 'b7de92234f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('task_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(op.f('tags_ibfk_1'), 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tags', 'tag_id')
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.add_column('tags', sa.Column('tag_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key(op.f('tags_ibfk_1'), 'tags', 'tasks', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tags', 'task_id')
    # ### end Alembic commands ###
